

spring:
  application:
    name: core-user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/core_user
    username: core
    password: core

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    #clean-disabled=false:
    # baseline-on-migrate: true


server:
  port: 8081






logging:
  level:
    root: INFO          # keep global level at INFO
    org.springframework.web: DEBUG
    org.springframework.http.converter: DEBUG
    org.springframework.validation: DEBUG
    org.springframework.web.servlet.mvc.method.annotation: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    feign.Logger: DEBUG
    com.orchestration.metadata: DEBUG   # <== your own package
    org.springframework.cloud.gateway.filter.factory.CircuitBreakerGatewayFilterFactory: DEBUG
    io.github.resilience4j.circuitbreaker: DEBUG